# Generated by Django 5.2 on 2025-04-29 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='robot',
            options={'verbose_name': 'Robot', 'verbose_name_plural': 'Robots'},
        ),
    ]
