# Generated by Django 5.1.6 on 2025-04-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'Usuario'), ('ADMIN', 'Administrador'), ('REST', 'Restaurante'), ('DRIVER', 'Conductor')], default='USER', max_length=8),
        ),
    ]
