# Generated by Django 5.1.6 on 2025-04-06 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
