# Generated by Django 5.2 on 2025-04-22 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
